# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SopraSteriaInitiative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SopraSteriaInitiative
  pod 'LinkedinSwift', '~> 1.6.6'

  target 'SopraSteriaInitiativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SopraSteriaInitiative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SopraSteriaInitiative-tvOS

  target 'SopraSteriaInitiative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
